name: docs

on:
  push:
  release:
    types:
      - published

permissions:
  contents: write

jobs:

  initial_research_doc:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/latex-pygments:latest
        with:
          args: ./initial_research/make.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: INITIAL_RESEARCH_DOC
          path: ./initial_research/INITIAL_RESEARCH_DOC.pdf

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Thesis --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v0.2
          FILES: ./initial_research/INITIAL_RESEARCH_DOC.pdf
