name: docs

on:
  push:
    tags:
      - "v0.0.1"

jobs:

  initial_research_doc:
    runs-on: ubuntu-latest


    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/latex-pygments:latest
        with:
          args: ./initial_research/make.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: INITIAL_RESEARCH_DOC
          path: ./initial_research/INITIAL_RESEARCH_DOC.pdf

      - name: Upload artifact to the tag
        uses: softprops/action-gh-release@v2
        with:
          files: ./initial_research/INITIAL_RESEARCH_DOC.pdf
          token: GITHUB_TOKEN
