name: Simulation

on:
  push:
  release:
    types:
      - published

permissions:
  contents: write

jobs:

  DAC_serial_dac856x:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 'Run DAC serial_dac856x sim'
        uses: docker://docker.io/ghdl/ext
        with:
          args: ./sim/dac/job_DAC_serial_dac856x.sh

      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: DAC_SIM_FILES
          path: |
            ./wave_dac.vcd
            ./tb_dac.csv

      - name: '📤 Upload WAVE to Release Assets'
        run: gh release upload --repo Unike267/Thesis --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v0.2
          FILES: |
            ./wave_dac.vcd
            ./tb_dac.csv
