name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  submodule_check:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 'Pulse_gen: analysis and elaboration test'
        run: |
          podman pull docker.io/ghdl/ext
          podman run --rm -tv $(pwd):/wrk:Z -w /wrk ghdl/ext sh -c "
          mkdir -p build \
          && ghdl -a --std=08 --workdir=build ./wr-cores/modules/timing/pulse_gen.vhd \
          && ghdl -e --std=08 --workdir=build pulse_gen \
          && cd build \
          && ls -l"
